
server:
  tomcat:
    max-threads: 3000
    min-spare-threads: 10
  port: 8761
spring:
  application:
    name: fml-eureka-server
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
    should-unregister-on-shutdown: true
    register-with-eureka: false
    fetch-registry: false
