
server:
  tomcat:
    max-threads: 3000
    min-spare-threads: 10
  port: 8761
spring:
  application:
    name: fml-eureka-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&&serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: select 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  transaction:
    rollback-on-commit-failure: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    should-unregister-on-shutdown: true
    register-with-eureka: false
    fetch-registry: true
